extern const GeoLayout ssl_area_1_geo[];
extern const GeoLayout ssl_area_1[];
extern const Collision ssl_area_1_collision[];
extern const MacroObject ssl_area_1_macro_objs[];
extern Lights1 ssl_dl_Ground_lights;
extern Lights1 ssl_dl_Cube_lights;
extern u8 ssl_dl_Planks_rgba16[];
extern Vtx ssl_dl_Ground_mesh_layer_1_vtx_0[4];
extern Gfx ssl_dl_Ground_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Ground_mesh_layer_1_vtx_1[120];
extern Gfx ssl_dl_Ground_mesh_layer_1_tri_1[];
extern Gfx mat_ssl_dl_Ground[];
extern Gfx mat_ssl_dl_Cube[];
extern Gfx ssl_dl_Ground_mesh_layer_1[];
extern Gfx ssl_dl_material_revert_render_settings[];
