extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern Lights1 ccm_dl_Ground_lights;
extern Lights1 ccm_dl_Cube_lights;
extern u8 ccm_dl_Planks_rgba16[];
extern Vtx ccm_dl_Ground_mesh_layer_1_vtx_0[4];
extern Gfx ccm_dl_Ground_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Ground_mesh_layer_1_vtx_1[96];
extern Gfx ccm_dl_Ground_mesh_layer_1_tri_1[];
extern Gfx mat_ccm_dl_Ground[];
extern Gfx mat_ccm_dl_Cube[];
extern Gfx ccm_dl_Ground_mesh_layer_1[];
extern Gfx ccm_dl_material_revert_render_settings[];
