extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern Lights1 wf_dl_Ground_lights;
extern Lights1 wf_dl_Cube_lights;
extern u8 wf_dl_Planks_rgba16[];
extern Vtx wf_dl_Ground_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Ground_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Ground_mesh_layer_1_vtx_1[72];
extern Gfx wf_dl_Ground_mesh_layer_1_tri_1[];
extern Gfx mat_wf_dl_Ground[];
extern Gfx mat_wf_dl_Cube[];
extern Gfx wf_dl_Ground_mesh_layer_1[];
extern Gfx wf_dl_material_revert_render_settings[];
