extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern Lights1 jrb_dl_Ground_lights;
extern Lights1 jrb_dl_Cube_lights;
extern u8 jrb_dl_Planks_rgba16[];
extern Vtx jrb_dl_Ground_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Ground_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Ground_mesh_layer_1_vtx_1[48];
extern Gfx jrb_dl_Ground_mesh_layer_1_tri_1[];
extern Gfx mat_jrb_dl_Ground[];
extern Gfx mat_jrb_dl_Cube[];
extern Gfx jrb_dl_Ground_mesh_layer_1[];
extern Gfx jrb_dl_material_revert_render_settings[];
